name: Build-Docker-Image

on: [push]

jobs:
  builddockerimg:
    runs-on: ubuntu-latest
    env:
      TAG: pythonapi
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Build Docker Img
      run: docker build -t $TAG .

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 196236753581.dkr.ecr.us-east-1.amazonaws.com
        docker tag pythonapi:latest 196236753581.dkr.ecr.us-east-1.amazonaws.com/pythonapi:latest
        docker push 196236753581.dkr.ecr.us-east-1.amazonaws.com/pythonapi:latest

    - name: Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '196236753581.dkr.ecr.us-east-1.amazonaws.com/pythonapi:latest'
        security-checks: 'vuln,secret,config'
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload the scan result to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'
        category: 'image'